server:
  port: 7070

spring:
  application:
    name: order-service
  redis:
    port: 6379
    host: localhost
    database: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6060/eureka
    fetch-registry: true #不从注册中心拉取注册表

feign:
  hystrix:
    enabled: true  #开启Feign的熔断功能
  client:
    config:
      default:
        connectTimeout: 12000
        readTimeout: 12000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000


#ribbon:
#  eureka:
#    enabled:  false

#my-user-service:
#  ribbon:
#    listOfServers: http://localhost:6060,http://localhost:6066