server:
  port: 10010

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://order-service
          order: 0
          predicates:
            - Path=/order-server/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6060/eureka
